apiVersion: v1
kind: Pod
metadata:
  name: test-pod-no-resources
spec:
  containers:
    - name: nginx
      image: bitnami/nginx:latest
      # Missing CPU and memory requests/limits, should fail the policy
